### ISSUE TITLE
Babel Error

### ISSUE THREAD

**Issue by reo-yamashita** [sjmc11/tourguide-js#23]
Nextjs14 and pnpm got babel error.

```bash
  ⨯ ../../node_modules/.pnpm/@sjmc11+tourguidejs@0.0.10/node_modules/@sjmc11/tourguidejs/src/Tour.ts
Module parse failed: Unexpected token (37:13)
: You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
 |      * Primary elements
 |      */
 >     backdrop : HTMLElement
 |     dialog : HTMLElement
| 
 Import trace for requested module:../../node_modules/.pnpm/@sjmc11+tourguidejs@0.0.10/node_modules/@sjmc11/tourguidejs/src/Tour.ts
./src/utils/tourguide.tsx
```

**Comment by sjmc11** [comment]
Hi @jmanos - this could possibly be down to babel or webpack configuration.

I suggest making sure TypeScript and babel-loader are installed in your project & your babel config includes the typescript preset:

`{
  "presets": ["@babel/preset-env", "@babel/preset-typescript"]
}`

If it's not that or webpack config related, re-open this issue & I will look into it further. Thanks
