### ISSUE TITLE
Hide Prev at first step or if there is no actual prev step

### ISSUE THREAD

**Issue by manchumahara** [sjmc11/tourguide-js#3]
After the dialog is loaded we are in first step so there is no prev step, in that situation if the previous button id by default disabled then it will make better in ux.

**Comment by sjmc11** [comment]
Hi @manchumahara 

This has been resolved as of version 0.0.8 available on [NPM](https://www.npmjs.com/package/@sjmc11/tourguidejs).

If the tours activeStep is equal to 0, the previous button is disabled and a "disabled" class is added to the element. Feel free to customise this in CSS to hide the button entirely.

Thanks
