### ISSUE TITLE
autoScrollOffset Does not seem to work

### ISSUE THREAD

**Issue by Thimows** [sjmc11/tourguide-js#31]
First of all, thank you so much for this library. It works amazingly well.

I did run into the issue that "autoScrollOffset' does not work. It does not seem to do anything. This could be a really powerful feature as by default the library does not center the elements when it scrolls to them. 

-> https://tourguidejs.com/docs/options.html#option-autoscrolloffset

Let me know if there are any examples of this feature working and/or of this can be fixed in the next release!

**Comment by sjmc11** [comment]
Hi @Thimows 

Thanks for finding this issue.

The scroll offset was not being applied to step elements declared in array style, but was being applied to elements declared via data-attributes.

That should be resolved and fixed on release v0.0.14 available on NPM.

Let me know if the issue persists.

**Comment by Thimows** [comment]
@sjmc11 Thanks! This fixed the issue!
