### ISSUE TITLE
Tourguide CDN is not working

### ISSUE THREAD

**Issue by Cristian9** [sjmc11/tourguide-js#4]
tourguide cdn often throws http 520 error

**Comment by sjmc11** [comment]
Thanks for reporting the issue, however this does not relate to the TourGuide package itself.

It could be for any number of reasons out of my control and possibly something with unpkg.com.

I recommend you use the NPM installation of Tourguide JS, if you face any issues with that - then please do report them and be happy to help.

Several tests and I am able to access https://unpkg.com/@sjmc11/tourguidejs@0.0.7/dist/tour.js from various devices & networks.
