### ISSUE TITLE
Website is down

### ISSUE THREAD

**Issue by renatoayau** [sjmc11/tourguide-js#41]
Hey guys, today I was looking at the page and it's down, does anyone know why?

**Comment by binaryoverload** [comment]
It appears the domain has expired as of yesterday (2024-11-11)

![image](https://github.com/user-attachments/assets/20a0eeac-21f9-4c4d-b20b-9c5f2572d1d8)

**Comment by sjmc11** [comment]
Small billing issue now resolved. Website should be back up soon. Thanks
