### ISSUE TITLE
Back Button always `disabled`

### ISSUE THREAD

**Issue by ThornWalli** [sjmc11/tourguide-js#5]
Hello,

I noticed that the back button always disabled 🙃

**Example:** https://stackblitz.com/edit/vue-92nhbv

Thanks!

**Comment by sjmc11** [comment]
Hi @ThornWalli - thanks for spotting this. Looks like a bug introduced in the latest NPM release aimed at rectifying this issue: https://github.com/sjmc11/tourguide-js/issues/3

This should be a quick fix and will aim to have this addressed ASAP. I will update this issue when I have done so.

**Comment by ThornWalli** [comment]
Perfectly works! 👌

Thank you for the fast support. 🙂
