### ISSUE TITLE
`handleFinishTour()` does not exit tour if 'tg_tours_complete' is not set in localStorage

### ISSUE THREAD

**Issue by mjgwood** [sjmc11/tourguide-js#9]
I noticed that I have to click the 'Finish' button twice to close the tour modal if 'tg_tours_complete' isn't set yet, but only once if it is.

Am I correct in thinking that `exit()` should be called before the first `return` statement [here](https://github.com/sjmc11/tourguide-js/blob/f748481ae0cd5433e34f715841cdf382e2157f18/src/handlers/handleFinishTour.ts#L15-L26)?
```
if(this.options.completeOnFinish) {
    if (!localStorage.tg_tours_complete) {
        localStorage.tg_tours_complete = [tourGroup]
        return
    }
    const storageTours = (localStorage.tg_tours_complete as string).split(',')
    storageTours.push(tourGroup)
    localStorage.tg_tours_complete = storageTours
}
if(exit) await this.exit()
this.activeStep = 0
return true
```

**Comment by sjmc11** [comment]
Thanks for the PR. Tested and merged.
